image: node:8.12.0
pipelines:
   branches:
      master: #master branch
      - step:
         deployment: production
         caches:
         - node
         script:
         - yarn
         - npm install -g @vue/cli
         - npm install -g firebase-tools 
         - yarn build --modern
         - firebase deploy --only hosting --token=$FIREBASE_TOKEN --project $FIREBASE_PROJECT --non-interactive
   branches:
      develop: #develop branch
      - step:
         deployment: development
         caches:
         - node
         script:
         - yarn
         - npm install -g @vue/cli
         - npm install -g firebase-tools 
         - yarn build --modern
         - firebase deploy --only hosting --token=$FIREBASE_TOKEN --project $FIREBASE_PROJECT --non-interactive