name: Develop CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          yarn
          npm install -g @vue/cli
          npm install -g firebase-tools 
          yarn test:unit
          yarn build --modern --if-present
          firebase deploy --only hosting --token=$FIREBASE_TOKEN --project porfolio-bot-ipwpmm --non-interactive --only hosting:portfolio-bot-staging

        env:
          CI: true
